/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniExample */

#ifndef _Included_JniExample
#define _Included_JniExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniExample
 * Method:    exampleFunction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JniExample_exampleFunction
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
